### PR TITLE
Remove UK overlays for Middlesex and Wiltshire

### PR DESCRIPTION
**Pull request by manewitz**
This came up because we use carmen to populate a "subregion" dropdown that is loaded after a user selects a country. We had several people write in about the UK list not being accurate.

   [Middlesex](https://en.wikipedia.org/wiki/Middlesex) is a "Historic County" and [not ISO-recognized as a subregion](https://www.iso.org/obp/ui/#iso:code:3166:GB). [Wiltshire](https://en.wikipedia.org/wiki/Wiltshire) is a "Unitary Authority" and [already in the base library](https://github.com/carmen-ruby/carmen/blob/cd3e696c67c61d81850e1a057ade5abe12a66454/locale/overlay/en/world/gb.yml#L7-L8). Even if their classifications had been corrent, the overlays removed had placed them at the wrong level in the region/subregion yaml hierarchy.

   Before: 
   ```ruby
   > uk = Carmen::Country.named('United Kingdom')
   > uk.subregions.map(&:name).sort
   => [
       [0] "England",
       [1] "England and Wales",
       [2] "Great Britain",
       [3] "Middlesex",
       [4] "Northern Ireland",
       [5] "Scotland",
       [6] "United Kingdom",
       [7] "Wales; Cymru",
       [8] "Wiltshire"
   ]
   ```

   After:
   ```ruby
   > uk.subregions.map(&:name).sort
   => [
        [0] "England",
        [1] "England and Wales",
        [2] "Great Britain",
        [3] "Northern Ireland",
        [4] "Scotland",
        [5] "United Kingdom",
        [6] "Wales; Cymru",
      ]
   ```
   ------------------------------------------

   Before submitting the PR please make sure that you have done the following:

   * [X] I have read the [Wiki on how to make geographic changes](https://github.com/carmen-ruby/carmen/wiki/Contributing-Data) if this PR modifies geographic data
   * [X] I have added a CHANGELOG entry if appropriate

### CODE REVIEW

**Comment by manewitz** [comment]
@swcraig let me know how this looks when you have some bandwidth

**Comment by swcraig** [comment]
Thanks for the PR! I will take a closer look tomorrow.

**Comment by manewitz** [comment]
(airhorn intensifies) Thanks you!

**Comment by manewitz** [comment]
@swcraig any reason you are holding on pushing out the new version?

**Comment by swcraig** [comment]
@manewitz No particular reason, the new version is out now. I'll work on a more consistent release schedule going forward. Thanks again for the contribution.

**Pull request merged**
